# Generated by Django 5.2.7 on 2025-10-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=10)),
                ('state_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=10)),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MGNREGAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('approved_labour_budget', models.BigIntegerField(blank=True, null=True)),
                ('average_wage_rate', models.FloatField(blank=True, null=True)),
                ('average_days_employment', models.IntegerField(blank=True, null=True)),
                ('differently_abled_persons_worked', models.IntegerField(blank=True, null=True)),
                ('material_and_skilled_wages', models.FloatField(blank=True, null=True)),
                ('number_of_completed_works', models.IntegerField(blank=True, null=True)),
                ('number_of_gps_with_nil_exp', models.IntegerField(blank=True, null=True)),
                ('number_of_ongoing_works', models.IntegerField(blank=True, null=True)),
                ('persondays_central_liability', models.BigIntegerField(blank=True, null=True)),
                ('sc_persondays', models.BigIntegerField(blank=True, null=True)),
                ('sc_workers_against_active_workers', models.IntegerField(blank=True, null=True)),
                ('st_persondays', models.BigIntegerField(blank=True, null=True)),
                ('st_workers_against_active_workers', models.IntegerField(blank=True, null=True)),
                ('total_adm_expenditure', models.FloatField(blank=True, null=True)),
                ('total_exp', models.FloatField(blank=True, null=True)),
                ('wages', models.FloatField(blank=True, null=True)),
                ('total_households_worked', models.IntegerField(blank=True, null=True)),
                ('total_individuals_worked', models.IntegerField(blank=True, null=True)),
                ('total_active_job_cards', models.IntegerField(blank=True, null=True)),
                ('total_active_workers', models.IntegerField(blank=True, null=True)),
                ('total_hhs_completed_100_days', models.IntegerField(blank=True, null=True)),
                ('total_jobcards_issued', models.IntegerField(blank=True, null=True)),
                ('total_workers', models.IntegerField(blank=True, null=True)),
                ('total_works_takenup', models.IntegerField(blank=True, null=True)),
                ('women_persondays', models.BigIntegerField(blank=True, null=True)),
                ('percent_category_b_works', models.IntegerField(blank=True, null=True)),
                ('percent_expenditure_agriculture', models.FloatField(blank=True, null=True)),
                ('percent_nrm_expenditure', models.FloatField(blank=True, null=True)),
                ('percentage_payments_within_15_days', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgnrega.district')),
            ],
        ),
    ]
